### ISSUE TITLE
Minify just one file

### ISSUE THREAD

**Issue by landed1** [hustxiaoc/gulp-minify#12]
Hi
Trying to use and promote this as there doesnt seem to be good options for gulp and js minifiation yet...
I am falling down though as I am trying to specify a single file in the src...
Also needs ext documenting better - what other extensions would be minified other than js ?
Thanks for helping me to understand.

**Comment by kent-remi** [comment]
I'm sorry, but I do not fully understand the problem here.
Specify one file in the src is gulp.src('path/js/file.js')...
The package is using UglifyJS2, so will only work for JavaScript files obviously.
You can use .whatever as file-extension if you like, that's why you can specify it.
Try to run minify without options to see all defaults :)

**Comment by landed1** [comment]
Ahh thanks for the help - I will try again.

**Comment by landed1** [comment]
I removed all of the options to get it to work but then I have js errors and I am feeding bck for you here
jQuery(document).ready(function ($) {

  $('.scrollspy').scrollSpy()

is getting made into 

ion())}e(".scrollspy").scrollSpy(),e( 

Uncaught TypeError: e(...).scrollSpy is not a function

**Comment by kent-remi** [comment]
Does this code work without the minification?

**Comment by landed1** [comment]
Damn - this I was doing something stupid..apologies if I remember I will post here closing for now. But TY.
